import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  return (
    <div className="h-screen flex items-center justify-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex gap-4">
        <Link href="/">
          <a>About</a>
        </Link>
        <Link href="/about">
          <a>About</a>
        </Link>
      </div>
    </div>
  );
}
